services:
  app:
    image: menu-kako-roadview:latest
    container_name: menu-container
    restart: always
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm start"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: "food_roulette_user"
      POSTGRES_PASSWORD: "2461"
      POSTGRES_DB: "food_roulette_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: